Attribute VB_Name = "BBError"
Option Compare Database
Option Explicit

Public Sub BBErrorMSG(bErr As ErrObject, Optional FuncSubName As String = "")
 Dim msg As String
 Dim Desc As String
 
  If bErr.Number = 2105 Then
   Desc = "Ne možete na tu poziciju"
  Else
   Desc = bErr.Description
  End If
  
  msg = "Error # " & stR(bErr.Number) & " was generated by " _
            & bErr.Source & Chr(13) & Desc
            
  If FuncSubName <> "" Then
    msg = msg & vbCrLf & "Func/Sub: " & FuncSubName
  End If
  
   ' MsgBox Msg, , BBCFG.AppName, bErr.HelpFile, bErr.HelpContext
    MsgBox msg, , "QMegaTeh", bErr.HelpFile, bErr.HelpContext
End Sub


